apiVersion: batch/v1
kind: Job
metadata:
  name: kubeos-vault-sync
  namespace: vault-backend
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-configmap: 'vault-sync-int-config'
spec:
  # completions: 2
  # parallelism: 1
  # completionMode: Indexed  # required for the feature
  # backoffLimitPerIndex: 1  # maximal number of failures per index
  # maxFailedIndexes: 5      # maximal number of failed indexes before terminating the Job execution
  template:
    spec:
      restartPolicy: Never # required for the feature
      serviceAccountName: kubeos-vault-sync
      containers:
      - name: kubeos-vault-sync
        image:  rohitrustagi007/kubeos-vault-sync:6
        env:
        - name: NAMESPACE
          value: vault-backend
        - name: CM_NAME
          value: vaultrole
        