---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeos-vault-sync
  namespace: vault-backend
  labels:
    app.kubernetes.io/name: kubeos-vault-sync

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vault-backend
  name: configmap-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","configmaps"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: vault-backend
subjects:
- kind: ServiceAccount
  name: kubeos-vault-sync
  namespace: vault-backend
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io