apiVersion: v1
kind: Service
metadata:
  name: kubeos-vault-sync
  namespace: dev
  labels:
    metrics-scraper: prometheus
spec:
  selector:
    app: kubeos-vault-sync
  ports:
    - name: http
      port: 80
      targetPort: 80
