apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-sync-int-config
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "kubeos-vault-sync"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"


    "vault" = {
      "address" = "http://vault.vault-backend.svc.cluster.local:8200"
    }
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "kubeos-vault-sync"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }
