apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kubeos-vault-sync
namespace: dev
bases:
  - ../../base
commonAnnotations:
  app: kubeos-vault-sync
  backstage.io/kubernetes-id: "kubeos-vault-sync"
commonLabels:
  app: kubeos-vault-sync
  backstage.io/kubernetes-id: "kubeos-vault-sync"
# patchesStrategicMerge:
# - configmap_patch.yaml